# Generated by Django 2.2.3 on 2019-07-21 00:52

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('polls', '0002_auto_20190721_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
