# Generated by Django 2.2.3 on 2019-07-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('polls', '0003_auto_20190721_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
